[project]
name = "vlm-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.10.0.84",
    "spacy>=3.8.3",
    "transformers>=4.47.1",
    "xinfer>=0.3.2",
]
